# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Handong
tagline:          'Blog'
description:      '<a href="https://www.facebook.com/handongchoi" target="_blank">@handongchoi</a> 촨동의 블로그'
url:              http://handongchoi.com
baseurl:          /

author:
  name:           'Handong Choi'
  url:            https://www.facebook.com/handongchoi

paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/henrychoi7

# Gems
gems:             [jekyll-paginate, jekyll-gist]
