# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Handong
tagline:          'Blog'
description:      '<a href="https://www.facebook.com/handongchoi" target="_blank">촨동</a>의 블로그'
url:              https://handongchoi.com
baseurl:          /

author:
  name:           'Handong Choi'
  url:            https://www.facebook.com/handongchoi

paginate:         5
paginate_path:    "/page:num/"

# Custom vars
version:          1.8

github:
  repo:           https://github.com/henrychoi7

# Gems
gems:             [jekyll-paginate, jekyll-gist]
