# The URL the site will be built for
base_url = "https://handongchoi.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "material-dark"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The site theme to use.
theme = "xyblag"

title = "Henry Choi"
description = "Loves searching, learning things. Life in security."

generate_feed = true

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]

# Disqus shortname for comments by disqus, when not set comment section isn't displayed
disqus_shortname = "handongchoi"

author = "Handong Choi"

katex_enable = true

# This is the default menu
blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

[extra.social_links]
twitter = "https://twitter.com/h3nrychoi"
github = "https://github.com/henrychoi7"
# behance = "https://behance.net/xypnox"
# telegram = "https://t.me/h3nrychoi"