# The URL the site will be built for
base_url = "https://handongchoi.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# The theme to use for code highlighting.
# See below for list of allowed values.
# highlight_theme = "material-dark"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The site theme to use.
theme = "after-dark"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
# Put all your custom variables here

author = "Handong Choi"

# This is the default menu
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

after_dark_title = "Henry's Blog"

# specify an image for the big header at the top of the page.
# this will be a background cover image, so make it large enough
# so that it won't upscale enough to pixelate
# feather_header_image = "/theme_images/default.gif"

# if you want comments, add your disqus embed code here.  
# you can obtain a code on the disqus website.
# feather_disqus_code = "<div id='disqus_thread'></div><script> var disqus_config = ... etc ... etc ..."

# if you'd like people to be able to donate to you, you can include a donate link
# to be displayed in the footer of the website.
# feather_donate_link = "https://paypal.me/piedoomy"

# if you want analytics, add your tracking code HTML here.
# feather_analytics = "<script async src='https://www.googletagmanager.com/gtag/... etc ... etc ..."